[project]
name = 'bsic-staking-platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bsic-staking-platform]
path = 'contracts/bsic-staking-platform.clar'

epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
